"""
train.py
========
YOLOv8 Training Script — Surgical Instrument Detection
GPU: RTX 3050 4GB  |  Model: YOLOv8s  |  Local Training

Usage:
  python train.py

Requires:
  pip install ultralytics
"""

from pathlib import Path
from ultralytics import YOLO
import torch

# ── Sanity check ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  Surgical Instrument Detector — YOLOv8 Training")
    print("=" * 60)

    if torch.cuda.is_available():
        gpu = torch.cuda.get_device_name(0)
        vram = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f"✅ GPU detected: {gpu}  ({vram:.1f} GB VRAM)")
    else:
        print("⚠  No CUDA GPU found — training on CPU will be very slow!")
        print("   Make sure CUDA drivers + torch-cuda are installed.")
        input("   Press Enter to continue anyway, or Ctrl+C to abort...")

    # ── Config ────────────────────────────────────────────────────────────────────
    DATA_YAML   = Path("dataset_yolo/data.yaml")   # generated by convert_xml_to_yolo.py
    MODEL       = "yolov8s.pt"   # yolov8n.pt (faster) | yolov8s.pt (better accuracy)
    EPOCHS      = 100
    IMG_SIZE    = 416            # 416 = ~3× faster than 640 with workers=0 on Windows
                                 # Switch back to 640 only if accuracy is too low
    BATCH_SIZE  = 16             # Can increase batch since 416px uses less VRAM
    WORKERS     = 0              # 0 = load data in main process (safest on Windows)
    PROJECT     = "runs/surgical"
    RUN_NAME    = "yolov8s_instruments"
    EXIST_OK    = True             # don't create new numbered folders on rerun
    DEVICE      = 0              # GPU 0
    # ─────────────────────────────────────────────────────────────────────────────

    assert DATA_YAML.exists(), (
        f"\n❌ {DATA_YAML} not found!\n"
        "   Run first:  python convert_xml_to_yolo.py\n"
    )

    print(f"\n📋 Config:")
    print(f"   Model     : {MODEL}")
    print(f"   Epochs    : {EPOCHS}")
    print(f"   Batch     : {BATCH_SIZE}")
    print(f"   Img size  : {IMG_SIZE}px")
    print(f"   Data YAML : {DATA_YAML.resolve()}")
    print(f"   Output    : {PROJECT}/{RUN_NAME}")
    print()

    # ── Load model & train ────────────────────────────────────────────────────────
    model = YOLO(MODEL)  # downloads weights on first run

    results = model.train(
        data        = str(DATA_YAML),
        epochs      = EPOCHS,
        imgsz       = IMG_SIZE,
        batch       = BATCH_SIZE,
        device      = DEVICE,
        workers     = WORKERS,
        project     = PROJECT,
        name        = RUN_NAME,
        exist_ok    = EXIST_OK,
        # ── Augmentation (good for small datasets) ──
        hsv_h       = 0.015,
        hsv_s       = 0.7,
        hsv_v       = 0.4,
        degrees     = 10.0,
        translate   = 0.1,
        scale       = 0.5,
        fliplr      = 0.5,
        mosaic      = 1.0,
        mixup       = 0.1,
        # ── Training ──
        optimizer   = "AdamW",
        lr0         = 0.001,
        lrf         = 0.01,
        weight_decay= 0.0005,
        warmup_epochs=3,
        patience    = 30,         # early stopping: stop if no improvement for 30 epochs
        save_period = 10,         # save checkpoint every 10 epochs
        amp         = True,       # mixed precision — saves VRAM on RTX 3050
        cache       = False,      # set True if you have 16GB+ RAM
        verbose     = True,
    )

    print("\n" + "=" * 60)
    print("✅ Training complete!")
    best = Path(results.save_dir) / "weights" / "best.pt"   # use actual save dir
    print(f"🏆 Best model: {best.resolve()}")
    print("=" * 60)

    # ── Quick validation ──────────────────────────────────────────────────────────
    print("\n📊 Running validation on test set...")
    model_best = YOLO(str(best))
    metrics = model_best.val(
        data    = str(DATA_YAML),
        split   = "test",
        device  = DEVICE,
        imgsz   = IMG_SIZE,
        verbose = True,
    )
    print(f"\n📈 Test Results:")
    print(f"   mAP@0.5    : {metrics.box.map50:.4f}")
    print(f"   mAP@0.5:95 : {metrics.box.map:.4f}")
    print(f"   Precision  : {metrics.box.mp:.4f}")
    print(f"   Recall     : {metrics.box.mr:.4f}")

    print("\n⚡ Next step → run:  python export_model.py")
